"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import type { SupabaseClient } from "@supabase/supabase-js";
import { createClient } from "@/lib/supabase/server";
import { parseEmployeeCsv, type ImportResult } from "@/lib/employee-import";
import { rowMatchesLocation } from "@/lib/location-match";

interface IngestStats {
  inserted: number;
  updated: number;
  failed: number;
  skipped_other_location: number;
  failures: string[];
}

/**
 * Ingest a parsed employee CSV into ONE location. Filters parsed.records by
 * location name first, then upserts. Pure compute (no redirect / revalidate)
 * so it can be called by both the per-location action and the multi-location
 * fan-out action.
 */
async function ingestEmployeesForLocation(
  supabase: SupabaseClient,
  parsed: ImportResult,
  location: { id: string; name: string }
): Promise<IngestStats> {
  const stats: IngestStats = {
    inserted: 0,
    updated: 0,
    failed: 0,
    skipped_other_location: 0,
    failures: [],
  };

  const { data: existing } = await supabase
    .from("employees")
    .select("id, employee_name")
    .eq("location_id", location.id);

  const byName = new Map<string, string>();
  for (const e of existing ?? []) {
    byName.set(e.employee_name.toLowerCase(), e.id);
  }

  for (const rec of parsed.records) {
    if (!rowMatchesLocation(rec.location_label, location.name)) {
      stats.skipped_other_location += 1;
      continue;
    }
    try {
      const matchId = byName.get(rec.employee_name.toLowerCase());
      if (matchId) {
        // Only overwrite fields the new import actually has data for;
        // preserves manually-edited values if the source CSV is sparse.
        const updates: Record<string, unknown> = {
          employee_name: rec.employee_name,
          active: true,
        };
        if (rec.email !== null) updates.email = rec.email;
        if (rec.phone !== null) updates.phone = rec.phone;
        if (rec.hire_date !== null) updates.hire_date = rec.hire_date;
        if (rec.wage !== null) {
          updates.wage = rec.wage;
          updates.wage_pay_type = rec.wage_pay_type;
        }
        const { error } = await supabase
          .from("employees")
          .update(updates)
          .eq("id", matchId);
        if (error) throw error;
        stats.updated += 1;
      } else {
        // employee_code is auto-generated by the database default.
        const { error } = await supabase.from("employees").insert({
          location_id: location.id,
          employee_name: rec.employee_name,
          email: rec.email,
          phone: rec.phone,
          hire_date: rec.hire_date,
          wage: rec.wage,
          wage_pay_type: rec.wage_pay_type,
          active: true,
        });
        if (error) throw error;
        stats.inserted += 1;
      }
    } catch (e) {
      stats.failed += 1;
      stats.failures.push(`${rec.employee_name} (${location.name}): ${(e as Error).message}`);
    }
  }

  return stats;
}

/**
 * Resolve the list of locations a bulk upload should target.
 *  - scope=client → all locations under the given client_id
 *  - scope=all    → all locations system-wide
 */
async function resolveBulkTargetLocations(
  supabase: SupabaseClient,
  scope: "client" | "all",
  client_id: string | null
): Promise<{ id: string; name: string }[]> {
  let q = supabase.from("locations").select("id, name").order("name");
  if (scope === "client" && client_id) q = q.eq("client_id", client_id);
  const { data } = await q;
  return ((data ?? []) as Array<{ id: string; name: string }>);
}

export async function uploadEmployeesCsvAction(formData: FormData) {
  const location_id = String(formData.get("location_id") ?? "");
  const file = formData.get("file") as File | null;

  if (!location_id) {
    redirect(`/dashboard/locations?import_error=${encodeURIComponent("Missing location.")}`);
  }
  if (!file || file.size === 0) {
    redirect(
      `/dashboard/locations/${location_id}?import_error=${encodeURIComponent("No file uploaded.")}`
    );
  }

  const text = await file.text();
  const parsed = parseEmployeeCsv(text);

  if (parsed.errors.length > 0 && parsed.records.length === 0) {
    redirect(
      `/dashboard/locations/${location_id}?import_error=${encodeURIComponent(
        parsed.errors.join("; ")
      )}`
    );
  }

  const supabase = await createClient();
  const { data: locRow } = await supabase
    .from("locations")
    .select("id, name")
    .eq("id", location_id)
    .single();
  const location = (locRow as { id: string; name: string } | null) ?? {
    id: location_id,
    name: "",
  };

  const stats = await ingestEmployeesForLocation(supabase, parsed, location);

  revalidatePath(`/dashboard/locations/${location_id}`);
  revalidatePath("/dashboard/employees");

  const params = new URLSearchParams();
  params.set("inserted", String(stats.inserted));
  params.set("updated", String(stats.updated));
  params.set("inactive_skipped", String(parsed.inactive_skipped));
  if (stats.skipped_other_location > 0)
    params.set("skipped_other_location", String(stats.skipped_other_location));
  if (stats.failed > 0) params.set("failed", String(stats.failed));
  if (parsed.warnings.length > 0)
    params.set("warnings", parsed.warnings.slice(0, 3).join(" | "));
  if (stats.failures.length > 0)
    params.set("failure_detail", stats.failures.slice(0, 3).join(" | "));

  redirect(`/dashboard/locations/${location_id}?${params.toString()}`);
}

/**
 * Bulk-ingest a single CSV across many locations at once. Used by the
 * top-level Uploads page (scope=all) and by Client detail pages (scope=client).
 * The CSV's per-row Location column drives row → location routing; rows
 * tagged for a location not in the target set get silently skipped.
 */
export async function uploadEmployeesCsvBulkAction(formData: FormData) {
  const scope = String(formData.get("scope") ?? "all") as "client" | "all";
  const client_id = scope === "client" ? String(formData.get("client_id") ?? "") : null;
  const file = formData.get("file") as File | null;

  const redirectBase =
    scope === "client" && client_id
      ? `/dashboard/clients/${client_id}`
      : `/dashboard/uploads`;

  if (!file || file.size === 0) {
    redirect(`${redirectBase}?bulk_error=${encodeURIComponent("No file uploaded.")}`);
  }

  const text = await file.text();
  const parsed = parseEmployeeCsv(text);

  if (parsed.errors.length > 0 && parsed.records.length === 0) {
    redirect(
      `${redirectBase}?bulk_error=${encodeURIComponent(parsed.errors.join("; "))}`
    );
  }

  const supabase = await createClient();
  const targets = await resolveBulkTargetLocations(supabase, scope, client_id);
  if (targets.length === 0) {
    redirect(
      `${redirectBase}?bulk_error=${encodeURIComponent(
        scope === "client" ? "No locations under this client." : "No locations exist yet."
      )}`
    );
  }

  // Aggregate stats across all targets.
  const aggregated: IngestStats = {
    inserted: 0,
    updated: 0,
    failed: 0,
    skipped_other_location: 0,
    failures: [],
  };
  const perLocation: Array<{
    name: string;
    inserted: number;
    updated: number;
    failed: number;
  }> = [];

  for (const loc of targets) {
    const stats = await ingestEmployeesForLocation(supabase, parsed, loc);
    aggregated.inserted += stats.inserted;
    aggregated.updated += stats.updated;
    aggregated.failed += stats.failed;
    aggregated.skipped_other_location += stats.skipped_other_location;
    aggregated.failures.push(...stats.failures);
    perLocation.push({
      name: loc.name,
      inserted: stats.inserted,
      updated: stats.updated,
      failed: stats.failed,
    });
  }

  // The "skipped_other_location" aggregate is misleading when each row gets
  // checked against N locations (a row matching loc[0] is "skipped" by locs
  // [1..N-1]). Compute the true unmatched count instead: rows in the CSV
  // whose location_label doesn't match ANY target.
  const targetNames = new Set(targets.map((l) => l.name.toLowerCase()));
  let trulyUnmatched = 0;
  for (const rec of parsed.records) {
    const lbl = (rec.location_label ?? "").trim().toLowerCase();
    if (lbl && !targetNames.has(lbl)) trulyUnmatched += 1;
  }

  // Revalidate every touched location so their dashboards refresh.
  for (const loc of targets) revalidatePath(`/dashboard/locations/${loc.id}`);
  revalidatePath("/dashboard/employees");
  if (scope === "client" && client_id) revalidatePath(`/dashboard/clients/${client_id}`);
  revalidatePath("/dashboard/uploads");

  const params = new URLSearchParams();
  params.set("bulk_inserted", String(aggregated.inserted));
  params.set("bulk_updated", String(aggregated.updated));
  params.set("bulk_failed", String(aggregated.failed));
  params.set("bulk_inactive_skipped", String(parsed.inactive_skipped));
  params.set("bulk_unmatched", String(trulyUnmatched));
  params.set("bulk_locations", String(targets.length));
  // Per-location breakdown (compact). Only show locations that had at least
  // one row land — empty locations are noise.
  const breakdown = perLocation
    .filter((p) => p.inserted + p.updated + p.failed > 0)
    .map((p) => `${p.name}: ${p.inserted}+${p.updated}u${p.failed > 0 ? ` (${p.failed} failed)` : ""}`)
    .join(" · ");
  if (breakdown) params.set("bulk_breakdown", breakdown);
  if (aggregated.failures.length > 0)
    params.set("bulk_failure_detail", aggregated.failures.slice(0, 3).join(" | "));
  if (parsed.warnings.length > 0)
    params.set("bulk_warnings", parsed.warnings.slice(0, 3).join(" | "));

  redirect(`${redirectBase}?${params.toString()}`);
}
