"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { parseEmployeeCsv } from "@/lib/employee-import";
import { rowMatchesLocation } from "@/lib/location-match";

interface UpsertCounts {
  inserted: number;
  updated: number;
  failed: number;
}

export async function uploadEmployeesCsvAction(formData: FormData) {
  const location_id = String(formData.get("location_id") ?? "");
  const file = formData.get("file") as File | null;

  if (!location_id) {
    redirect(`/dashboard/locations?import_error=${encodeURIComponent("Missing location.")}`);
  }
  if (!file || file.size === 0) {
    redirect(
      `/dashboard/locations/${location_id}?import_error=${encodeURIComponent("No file uploaded.")}`
    );
  }

  const text = await file.text();
  const parsed = parseEmployeeCsv(text);

  if (parsed.errors.length > 0 && parsed.records.length === 0) {
    redirect(
      `/dashboard/locations/${location_id}?import_error=${encodeURIComponent(
        parsed.errors.join("; ")
      )}`
    );
  }

  const supabase = await createClient();
  const counts: UpsertCounts = { inserted: 0, updated: 0, failed: 0 };
  const failures: string[] = [];
  let skippedOtherLocation = 0;

  // Fetch the target location's name so we can filter all-locations CSV exports
  // down to rows for THIS location. If the CSV's row has no Location column at
  // all (single-location export), all rows pass through — backward compatible.
  const { data: locRow } = await supabase
    .from("locations")
    .select("name")
    .eq("id", location_id)
    .single();
  const targetLocationName = (locRow?.name as string | undefined) ?? "";

  // Match strategy (no external IDs from source): exact name match within location.
  const { data: existing } = await supabase
    .from("employees")
    .select("id, employee_name")
    .eq("location_id", location_id);

  const byName = new Map<string, string>();
  for (const e of existing ?? []) {
    byName.set(e.employee_name.toLowerCase(), e.id);
  }

  for (const rec of parsed.records) {
    if (!rowMatchesLocation(rec.location_label, targetLocationName)) {
      skippedOtherLocation += 1;
      continue;
    }
    try {
      const matchId = byName.get(rec.employee_name.toLowerCase());

      if (matchId) {
        // Only overwrite fields the new import actually has data for;
        // preserves manually-edited values if the source CSV is sparse.
        const updates: Record<string, unknown> = {
          employee_name: rec.employee_name,
          active: true,
        };
        if (rec.email !== null) updates.email = rec.email;
        if (rec.phone !== null) updates.phone = rec.phone;
        if (rec.hire_date !== null) updates.hire_date = rec.hire_date;
        if (rec.wage !== null) {
          updates.wage = rec.wage;
          updates.wage_pay_type = rec.wage_pay_type;
        }
        const { error } = await supabase
          .from("employees")
          .update(updates)
          .eq("id", matchId);
        if (error) throw error;
        counts.updated += 1;
      } else {
        // employee_code is auto-generated by the database default.
        const { error } = await supabase.from("employees").insert({
          location_id,
          employee_name: rec.employee_name,
          email: rec.email,
          phone: rec.phone,
          hire_date: rec.hire_date,
          wage: rec.wage,
          wage_pay_type: rec.wage_pay_type,
          active: true,
        });
        if (error) throw error;
        counts.inserted += 1;
      }
    } catch (e) {
      counts.failed += 1;
      failures.push(`${rec.employee_name}: ${(e as Error).message}`);
    }
  }

  revalidatePath(`/dashboard/locations/${location_id}`);
  revalidatePath("/dashboard/employees");

  const params = new URLSearchParams();
  params.set("inserted", String(counts.inserted));
  params.set("updated", String(counts.updated));
  params.set("inactive_skipped", String(parsed.inactive_skipped));
  if (skippedOtherLocation > 0)
    params.set("skipped_other_location", String(skippedOtherLocation));
  if (counts.failed > 0) params.set("failed", String(counts.failed));
  if (parsed.warnings.length > 0)
    params.set("warnings", parsed.warnings.slice(0, 3).join(" | "));
  if (failures.length > 0) params.set("failure_detail", failures.slice(0, 3).join(" | "));

  redirect(`/dashboard/locations/${location_id}?${params.toString()}`);
}
